# Generated by Django 4.1.3 on 2023-01-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=50)),
                ('resumen', models.CharField(max_length=500)),
                ('director_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoresCine.director')),
            ],
        ),
    ]
