# Generated by Django 4.1.3 on 2023-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=5)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
